### PR TITLE
Create haond_benchmark.md

### PR DESCRIPTION
**Pull request by nguyenduyhao1111**

### CODE REVIEW

**Comment by vietlq** [comment]
Well done! The most cryptic solution is the most efficient because you have optimized for the compiler using the array.

**Comment by longkt90** [comment]
Drop by this repo from launch facebook group, I think this PR need more improvement.
@nguyenduyhao1111 
1. Commit message - the is no need to commit a message say `Create a file`, git tells it already. Should be something has more information, e.g: `Adding benchmark for 3 Fizz-Buzz solution`

2. Function's name should tell what it does. Maybe: `fizz_buzz_solution_1`, `fizz_buzz_solution_2`, `fizz_buzz_solution_3`?

3. Coding style need more changes:
- Need space between operations, `i%3` => `i % 3`, ...
- Avoid use {} for multi-line blocks
```
 (1..n).each{|i|
    s = 'Fizz' if i%3 == 0
    s = 'Buzz' if i%5 == 0
  }      
```

should be like:

```
(1..n).each do |i|
  puts 'Fizz' if i % 3 == 0
  puts 'Buzz' if i % 5 == 0
end
```

- A lot more 💃

**Comment by vietlq** [comment]
Hi Long,

You should submit a PR. As for commit message, that's separate issue.

**Comment by longkt90** [comment]
I will let it here for @nguyenduyhao1111 if he wants to do it :)

**Comment by vietlq** [comment]
I mean if you want to submit PR for yourself. As for Hao, I'm not sure if you both are closely related and whether he enjoys unsolicited comments. So I would encourage you to submit your own PR and leave Hao alone. Thanks.

**Comment by longkt90** [comment]
> Các bạn software engineers, start-up, sinh viên CNTT tò mò về cách tuyển dụng và muốn tìm các câu hỏi phỏng vấn thực tiễn trong công việc và không mang tính chất đánh đố thì có thể tham khảo trang này của mình:
> 
> http://www.code2.pro/p/sample-technical-interview-questions/
> 
> Hiện mình để miễn phí cho cộng đồng và các bạn có thể tham gia, giải, để lại comment hoặc request thêm.
> 
> Mình nhận làm tư vấn xây dựng hiring framework và làm mock interview cho các công ty hay các dev có nhu cầu nhé.
> 
> Ai muốn mình làm code review thì fork và gửi lên GitHub nhé. Rất chuyên nghiệp và minh bạch:
> 
> https://github.com/DevVietRaKhoi/weekly

Well I thought you're welcome outsiders to contribute by `tham gia, giải, để lại comment hoặc request thêm`. If you mean it's only for you to review then just ignore me.

**Comment by vietlq** [comment]
I should make myself clear: This repo for individual solutions and.

For code2.pro course on sample questions, you can make comments as I opened comment section.

There's clear separation between two. When I have a collaborative project on GitHub, I will announce for collaboration.

As for this repo, you should do own work. You can send comments on the sample interview questions.

**Comment by nguyenduyhao1111** [comment]
Thank for @longkt90 and @vietlq  . Be nice!

**Comment by vietlq** [comment]
Thanks Long for comments and Hao for the updates.

Long: If you are keen on particular projects like interview, algos & data structures, effective & scalable design, let me know. We can host collaborative projects for community.

**Comment by vietlq** [comment]
"Ai muốn mình làm code review thì fork và gửi lên GitHub nhé. Rất chuyên nghiệp và minh bạch:

https://github.com/DevVietRaKhoi/weekly"

I clearly stated that I will do code review for this repo so it's regrettable you misuderstood it :) You are welcome to join the code2.pro page and comment.

**Comment by longkt90** [comment]
Hi, Thanks for the clarification and for your contributions for Vietnamese developers community. I do want the best for our community too :)

**Comment by vietlq** [comment]
Great! Thank you for kind words. I want to know more people and work with developers through basic data structures & algos course first and then think about community projects and FOSS projects when everyone got necessary skills.

Vietnam is not exactly known for contributing to FOSS. I know only Unikey, but there are more :)

**Pull request merged**
